/* Generated By:JavaCC: Do not edit this line. ExprsParseConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExprsParseConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT = 5;
  /** RegularExpression Id. */
  int IF = 6;
  /** RegularExpression Id. */
  int WHILE = 7;
  /** RegularExpression Id. */
  int FINAL = 8;
  /** RegularExpression Id. */
  int ELSE = 9;
  /** RegularExpression Id. */
  int COMPOP = 10;
  /** RegularExpression Id. */
  int NUMBER = 11;
  /** RegularExpression Id. */
  int IDENT = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"int\"",
    "\"if\"",
    "\"while\"",
    "\"final\"",
    "\"else\"",
    "<COMPOP>",
    "<NUMBER>",
    "<IDENT>",
    "\";\"",
    "\"=\"",
    "\",\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"print(\"",
    "\");\"",
    "\"{\"",
    "\"}\"",
  };

}
